package com.SmartTech.teasyNew.model;

import java.util.ArrayList;
import java.util.List;

public enum Bank {

    SterlingBank("000001","Sterling Bank",Type.BANK)	,
    KeystoneBank("000002","Keystone Bank",Type.BANK)	,
    FCMB("000003","First City Monument Bank (FCMB)",Type.BANK	)	,
    UnitedBankforAfrica("000004","United Bank for Africa (UBA)",Type.BANK),
    DiamondBank("000005",	"Diamond Bank",Type.BANK),
    JAIZBank("000006","JAIZ Bank",Type.BANK),
    FidelityBank("000007","Fidelity Bank",Type.BANK),
    PolarisBank("000008",	"Polaris Bank",	Type.BANK),
    CitiBank("000009","Citi Bank",Type.BANK),
    EcobankBank("000010","Eco bank",Type.BANK)	,
    UnityBank("000011",	"Unity Bank",Type.BANK)	,
    StanbicIBTCBank("000012","Stanbic IBTC Bank",Type.BANK),
    GTBankPlc("000013",	"GT Bank Plc",Type.BANK),
    AccessBank("000014","Access Bank"	,	Type.BANK),
    ZenithBankPlc("000015	","Zenith Bank Plc", Type.BANK),
    FirstBankofNigeria("000016","First Bank of Nigeria", Type.BANK),
    WemaBank("000017","Wema Bank"	,Type.BANK),
    UnionBank("000018","Union Bank",Type.BANK),
    EnterpriseBank("000019","Enterprise Bank",Type.BANK),
    Heritage("000020","Heritage Bank",Type.BANK),
    StandardChartered("000021","Standard Chartered",Type.BANK),
    SuntrustBank("000022","Sun trust Bank",Type.BANK),
    ProvidusBank("000023","Providus Bank",Type.BANK),
    RandMerchantBank("000024","Rand Merchant Bank",Type.BANK),
    TitanTrustBank("000025","Titan Trust Bank",Type.BANK),
    TajBank("000026","Taj Bank",Type.BANK),
    GlobusBank("000027","Globus Bank",Type.BANK),
    LotusBank("000029","Lotus Bank",Type.BANK),
    PremiumTrustBank("000031","Premium Trust Bank",Type.BANK),
    eNaira("000033","eNaira",Type.BANK),
    SignatureBank("000034","Signature Bank",Type.BANK),
    OptimusBank("000036",	"Optimus Bank",	Type.BANK),
    ParallexBank("000030"	,"Parallex Bank",	Type.BANK),
    FEWCHOREFINANCECOMPANYLIMITED("050002",	"FEWCHORE FINANCE COMPANY LIMITED",Type.BANK),
    SageGreyFinanceLimited(	"050003",	"SageGrey Finance Limited",	Type.BANK),
    AAAFinance(	"050005"	,"AAA Finance"	,	Type.BANK	),
    BranchInternationalFinancialServices("050006"	,"Branch International Financial Services",Type.BANK),
    TeklaFinanceLimited("050007"	,	"Tekla Finance Limited"	,	Type.BANK),
    FastCredit("050009",	"Fast Credit",	Type.BANK),
    FundquestFinancialServicesLimited("050010",	"Fundquest Financial Services Limited",Type.BANK),
    EncoFinance("050012",	"Enco Finance",Type.BANK	),
    DignityFinance("050013",	"Dignity Finance",Type.BANK),
    TrinityFinancialServicesLimited(	"050013"	,	"Trinity Financial Services Limited",	Type.BANK),
    SimpleFinanceLimited(	"050008",	"Simple Finance Limited",Type.BANK),
    LukefieldFinanceCompanyLimited(	"050015"	,	"Lukefield Finance Company Limited",Type.BANK),
    FSDHMerchantBank("400001"	,	"FSDH Merchant Bank",Type.BANK),
    CoronationMerchantBank("060001",	"Coronation Merchant Bank",	Type.BANK),
    FBNQUESTMerchantBank("060002",	"FBN QUEST Merchant Bank",Type.BANK),
    NovaMerchantBank("060003",	"Nova Merchant Bank"	,	Type.BANK)	,
    GreenwichMerchantBank(	"060004",	"Greenwich Merchant Bank"	,	Type.BANK	)	,
    Omoluabisavingsandloans("070007","Omoluabi savings and loans",Type.BANK)	,
    ASOSavingsLoans(	"090001"	,	"ASO Savings & Loans	",Type.BANK	),
    TrustbondMortgageBank(	"090005"	,	"Trustbond Mortgage Bank"	,	Type.BANK	)	,
    SafeTrust(	"	090006"	,	"Safe Trust",	Type.BANK),
    FBNMortgagesLimited(	"090107"	,	"FBN Mortgages Limited"	,	Type.BANK),
    ImperialHomesMortgageBank(	"100024"	,	"Imperial Homes Mortgage Bank",	Type.BANK),
    AGMortgageBank(	"100028",	"AG Mortgage Bank",	Type.BANK),
    GatewayMortgageBank(	"070009",	"Gateway Mortgage Bank",Type.BANK)	,
    AbbeyMortgageBank(	"070010",	"Abbey Mortgage Bank"	,	Type.BANK)	,
    RefugeMortgageBank(	"070011",	"Refuge Mortgage Bank",	Type.BANK)	,
    LagosBuildingInvestmentCompany(	"070012"	,	"Lagos Building Investment Company"	,	Type.BANK	)	,
    PlatinumMortgageBank(	"070013"	,	"Platinum Mortgage Bank"	,	Type.BANK	)	,
    FirstGenerationMortgageBank(	"070014"	,	"First Generation Mortgage Bank"	,	Type.BANK	)	,
    BrentMortgageBank(	"070015"	,	"Brent Mortgage Bank"	,	Type.BANK	)	,
    InfinityTrustMortgageBank(	"070016"	,	"Infinity Trust Mortgage Bank"	,	Type.BANK	)	,
    MayFreshMortgageBank("070019"	,	"MayFresh Mortgage Bank",	Type.BANK)	,
    JubileeLifeMortgageBank("090003"	,	"Jubilee-Life Mortgage Bank"	,	Type.BANK)	,
    HaggaiMortgageBankLimited("070017"	,	"Haggai Mortgage Bank Limited",	Type.BANK)	,
    CoopMortgageBank("070021"	,	"Coop Mortgage Bank"	,	Type.BANK	)	,
    STBMortgageBank("	070022"	,	"STB Mortgage Bank"	,	Type.BANK	)	,
    DeltaTrustMicrofinanceBank(	"070023"	,	"DeltaTrustMicrofinanceBank",Type.BANK	)	,
    HomebaseMortgageBank(	"070024"	,	"Homebase Mortgage Bank"	,	Type.BANK	)	,
    AkwaSavingsLoansLimited(	"070025"	,	"Akwa Savings & Loans Limited"	,	Type.BANK	)	,
    FHAMortgageBank(	"070026"	,	"FHA Mortgage Bank"	,Type.BANK	)	,
    NewPrudentialBank(	"090108"	,	"New Prudential Bank"	,Type.BANK	)	,
    NPFMicroFinanceBank(	"070001"	,	"NPF MicroFinance Bank"	,	Type.BANK	)	,
    FortisMicrofinanceBank(	"070002"	,	"Fortis Microfinance Bank	"	,	Type.BANK	)	,
    CovenantMFB(	"070006"	,	"Covenant MFB"	,	Type.BANK	)	,
    PageFinancials(	"070008"	,	"Page Financials"	,	Type.BANK	)	,
    ParralexMicrofinancebank(	"090004"	,"Parralex Microfinance Bank"	,	Type.BANK	)	,
    EkondoMFB(	"090097"	,	"Ekondo MFB	"	,	Type.BANK	)	,
    VFDMFB(	"090110"	,	"VFD MFB"	,	Type.BANK	)	,
    FinaTrustMicrofinanceBank(	"090111"	,	"FinaTrust Microfinance Bank"	,	Type.BANK	)	,
    SeedCapitalMicrofinanceBank(	"090112"	,	"Seed Capital Microfinance Bank	"	,	Type.BANK	)	,
    EmpiretrustMFB(	"090114"	,	"Empiretrust MFB"	,	Type.BANK	)	,
    TCFMFB(	"090115"	,	"TCF MFB"	,	Type.BANK	)	,
    AMMLMFB("090116"	,	"AMML MFB"	,	Type.BANK	)	,
    BoctrustMicrofinanceBank("090117"	,	"Boctrust Microfinance Bank"	,	Type.BANK)	,
    IBILEMicrofinanceBank(	"090118"	,	"IBILE Microfinance Bank"	,	Type.BANK)	,
    OhafiaMicrofinanceBank(	"090119"	,	"Ohafia Microfinance Bank"	,	Type.BANK)	,
    WetlandMicrofinanceBank(	"090120"	,	"Wetland Microfinance Bank"	,	Type.BANK)	,
    HasalMicrofinanceBank(	"090121"	,	"Hasal Microfinance Bank"	,	Type.BANK)	,
    GowansMicrofinanceBank(	"090122"	,	"Gowans Microfinance Bank"	,	Type.BANK)	,
    VeriteMicrofinanceBank(	"090123"	,	"Verite Microfinance Bank"	,	Type.BANK)	,
    XslnceMicrofinanceBank(	"090124"	,	"Xslnce Microfinance Bank"	,	Type.BANK)	,
    RegentMicrofinanceBank(	"090125"	,	"Regent Microfinance Bank"	,	Type.BANK)	,
    FidfundMicrofinanceBank(	"090126"	,	"Fidfund Microfinance Bank"	,	Type.BANK)	,
    BCKashMicrofinanceBank(	"090127"	,	"BCKash Microfinance Bank"	,	Type.BANK)	,
    NdiorahMicrofinanceBank(	"090128"	,	"Ndiorah Microfinance Bank"	,	Type.BANK)	,
    MoneyTrustMicrofinanceBank(	"090129"	,	"Money TrustMicrofinance Bank"	,	Type.BANK)	,
    ConsumerMicrofinanceBank(	"090130"	,	"Consumer Microfinance Bank"	,	Type.BANK)	,
    AllworkersMicrofinanceBank(	"090131"	,	"Allworkers Microfinance Bank"	,	Type.BANK)	,
    RichwayMicrofinanceBank(	"090132"	,	"Richway Microfinance Bank"	,	Type.BANK)	,
    ALBarakahMicrofinanceBank(	"090133"	,	"AL-Barakah Microfinance Bank"	,	Type.BANK)	,
    AccionMicrofinanceBank(	"090134"	,	"Accion Microfinance Bank"	,	Type.BANK)	,
    PersonalTrustMicrofinanceBank(	"090135"	,	"PersonalTrustMicrofinanceBank"	,Type.BANK)	,
    MicrocredMicrofinanceBank(	"090136"	,	"Microcred Microfinance Bank"	,	Type.BANK	)	,
    PecanTrustMicrofinanceBank(	"090137"	,	"PecanTrust Microfinance Bank"	,	Type.BANK	)	,
    RoyalExchangeMicrofinanceBank(	"090138"	,	"RoyalExchange Microfinance Bank"	,	Type.BANK	)	,
    VisaMicrofinanceBank(	"090139"	,	"Visa Microfinance Bank	"	,	Type.BANK	)	,
    SagamuMicrofinanceBank(	"090140"	,	"Sagamu Microfinance Bank"	,	Type.BANK	)	,
    ChikumMicrofinanceBank(	"090141"	,	"Chikum Microfinance Bank"	,	Type.BANK	)	,
    YesMicrofinanceBank(	"090142"	,	"Yes Microfinance Bank"	,	Type.BANK	)	,
    ApeksMicrofinanceBank(	"090143"	,	"Apeks Microfinance Bank"	,	Type.BANK	)	,
    CITMicrofinanceBank(	"090144"	,	"CIT Microfinance Bank"	,	Type.BANK	)	,
    FullrangeMicrofinanceBank(	"090145"	,	"Fullrange Microfinance Bank"	,	Type.BANK	)	,
    TridentMicrofinanceBank(	"090146"	,	"Trident Microfinance Bank"	,	Type.BANK	)	,
    HackmanMicrofinanceBank(	"090147"	,	"Hackman Microfinance Bank"	,	Type.BANK	)	,
    BowenMicrofinanceBank(	"090148"	,	"Bowen Microfinance Bank"	,	Type.BANK	)	,
    IRLMicrofinanceBank(	"090149"	,	"IRL Microfinance Bank"	,	Type.BANK	)	,
    VirtueMicrofinanceBank(	"090150"	,	"Virtue Microfinance Bank"	,	Type.BANK	)	,
    MutualTrustMicrofinanceBank(	"090151"	,	"Mutual Trust Microfinance Bank	"	,	Type.BANK	)	,
    NagartaMicrofinanceBank(	"090152"	,	"Nagarta Microfinance Bank"	,	Type.BANK	)	,
    FFSMicrofinanceBank(	"090153"	,	"FFS Microfinance Bank"	,	Type.BANK	)	,
    CEMCSMicrofinanceBank(	"090154"	,	"CEMCS Microfinance Bank",	Type.BANK	)	,
    AdvansLaFayetteMicrofinanceBank(	"090155"	,	"Advans La Fayette MicrofinanceBank"	,	Type.BANK	)	,
    eBarcsMicrofinanceBank(	"090156"	,	"e-Barcs Microfinance Bank"	,	Type.BANK	)	,
    InfinityMicrofinanceBank(	"090157"	,	"Infinity Microfinance Bank"	,	Type.BANK	)	,
    FutoMicrofinanceBank(	"090158"	,	"Futo Microfinance Bank"	,	Type.BANK	)	,
    CreditAfriqueMicrofinanceBank(	"090159"	,	"Credit Afrique Microfinance Bank"	,	Type.BANK	)	,
    AddosserMicrofinanceBank(	"090160"	,	"Addosser Microfinance Bank"	,	Type.BANK	)	,
    OkpogaMicrofinanceBank(	"090161"	,	"Okpoga Microfinance Bank"	,	Type.BANK	)	,
    StanfordMicrofinanceBak(	"090162"	,	"Stanford Microfinance Bank"	,	Type.BANK	)	,
    FirstRoyalMicrofinanceBank(	"090164"	,	"		FirstRoyalMicrofinanceBank"	,	Type.BANK	)	,
    PetraMicrofinanceBank(	"090165"	,	"		Petra Microfinance Bank"	,	Type.BANK	)	,
    EsoEMicrofinanceBank(	"090166"	,	"Eso-E Microfinance Bank"	,	Type.BANK	)	,
    DaylightMicrofinanceBank(	"	090167"	,	"Daylight Microfinance Bank"	,	Type.BANK	)	,
    GashuaMicrofinanceBank(	"090168"	,	"Gashua Microfinance Bank"	,	Type.BANK	)	,
    AlphaKapitalMicrofinanceBank(	"090169"	,	"AlphaKapital Microfinance Bank"	,	Type.BANK	)	,
    MainstreetMicrofinanceBank(	"090171"	,	"Mainstreet Microfinance Bank"	,	Type.BANK	)	,
    AstrapolarisMicrofinanceBank(	"090172"	,	"Astrapolaris Microfinance Bank"	,	Type.BANK	)	,
    RelianceMicrofinanceBank(	"090173"	,	"Reliance Microfinance Bank"	,	Type.BANK	)	,
    MalachyMicrofinanceBank(	"090174"	,	"Malachy Microfinance Bank"	,	Type.BANK	)	,
    HighStreetMicrofinanceBank(	"090175"	,	"HighStreet Microfinance Bank"	,	Type.BANK	)	,
    BosakMicrofinanceBank(	"090176"	,	"Bosak Microfinance Bank"	,	Type.BANK	)	,
    LapoMicrofinanceBank(	"090177"	,	"Lapo Microfinance Bank"	,	Type.BANK	)	,
    GreenBankMicrofinanceBank(	"090178"	,	"GreenBank Microfinance Bank"	,	Type.BANK	)	,
    FASTMicrofinanceBank(	"090179"	,	"FAST Microfinance Bank"	,	Type.BANK	)	,
    AmjuUniqueMicrofinanceBank(	"090180"	,	"Amju Unique Microfinance Bank	"	,	Type.BANK	)	,
    GireiMicrofinanceBank(	"090186"	,	"Girei Microfinance Bank"	,	Type.BANK	)	,
    BainesCreditMicrofinanceBank(	"090188"	,	"Baines Credit Microfinance Bank"	,	Type.BANK	)	,
    EsanMicrofinanceBank(	"090189	"	,	"Esan Microfinance Bank"	,	Type.BANK	)	,
    MutualBenefitsMicrofinanceBank(	"	090190	"	,	"Mutual Benefits Microfinance Bank"	,	Type.BANK	)	,
    KCMBMicrofinanceBank(	"	090191"	,	"KCMB Microfinance Bank"	,	Type.BANK	)	,
    MidlandMicrofinanceBank(	"090192"	,	"Midland Microfinance Bank	"	,	Type.BANK	)	,
    UnicalMicrofinanceBank(	"090193"	,	"Unical Microfinance Bank"	,	Type.BANK	)	,
    NIRSALMicrofinanceBank(	"090194"	,	"NIRSAL Microfinance Bank"	,	Type.BANK	)	,
    GroomingMicrofinanceBank(	"090195"	,	"Grooming Microfinance Bank"	,	Type.BANK	)	,
    PennywiseMicrofinanceBank(	"090196"	,	"Pennywise Microfinance Bank"	,	Type.BANK	)	,
    ABUMicrofinanceBank(	"090197"	,	"ABU Microfinance Bank"	,	Type.BANK	)	,
    RenMoneyMicrofinanceBank(	"090198"	,	"RenMoney Microfinance Bank	"	,	Type.BANK	)	,
    NewDawnMicrofinanceBank(	"090205"	,	"NewDawn Microfinance Bank	"	,	Type.BANK	)	,
    UNNMFB(	"090251"	,	"UNN MFB"	,	Type.BANK	)	,
    YobeMicrofinanceBank(	"090252"	,	"Yobe Microfinance Bank"	,	Type.BANK	)	,
    CoalcampMicrofinanceBank(	"090254"	,	"Coalcamp Microfinance Bank"	,	Type.BANK	)	,
    ImoStateMicrofinanceBank(	"090258"	,	"ImoState Microfinance Bank"	,	Type.BANK	)	,
    AlekunMicrofinanceBank(	"090259"	,	"Alekun Microfinance Bank"	,	Type.BANK	)	,
    AboveOnlyMicrofinanceBank(	"090260"	,	"AboveOnly Microfinance Bank"	,	Type.BANK	)	,
    QuickfundMicrofinanceBank(	"090261"	,	"Quickfund Microfinance Bank"	,	Type.BANK	)	,
    StellasMicrofinanceBank(	"090262"	,	"Stellas Microfinance Bank"	,	Type.BANK	)	,
    NavyMicrofinanceBank(	"090263"	,	"Navy Microfinance Bank"	,	Type.BANK	)	,
    AuchiMicrofinanceBank(	"090264"	,	"Auchi Microfinance Bank"	,	Type.BANK	)	,
    LovonusMicrofinanceBank(	"090265"	,	"Lovonus Microfinance Bank"	,	Type.BANK	)	,
    UnibenMicrofinanceBank(	"090266"	,	"Uniben Microfinance Bank	"	,	Type.BANK	)	,
    KudaMicrofinanceBank(	"090267"	,	"Kuda Microfinance Bank"	,	Type.BANK	)	,
    AdeyemiCollegeStaffMicrofinanceBank(	"090268"	,	"AdeyemiCollegeStaff Microfinance Bank"	,	Type.BANK	)	,
    GreenvilleMicrofinanceBank(	"090269"	,	"Greenville Microfinance Bank"	,	Type.BANK	)	,
    ABMicrofinanceBank(	"090270"	,	"ABMicrofinanceBank"	,	Type.BANK	)	,
    LavenderMicrofinanceBank(	"090271"	,	"LavenderMicrofinanceBank	"	,	Type.BANK	)	,
    OlabisiOnabanjoUniversityMicrofinanceBank(	"090272"	,	"Olabisi Onabanjo University Microfinance Bank"	,	Type.BANK	)	,
    EmeraldsMicrofinanceBank(	"090273"	,	"Emeralds Microfinance Bank"	,	Type.BANK	)	,
    PrestigeMicrofinanceBank(	"090274"	,	"Prestige Microfinance Bank"	,	Type.BANK	)	,
    TrustfundMicrofinanceBank(	"090276"	,	"Trustfund Microfinance Bank"	,	Type.BANK	)	,
    AlHayatMicrofinanceBank(	"090277"	,	"Al-Hayat Microfinance Bank"	,	Type.BANK	)	,
    GloryMicrofinanceBank(	"090278"	,	"Glory Microfinance Bank"	,	Type.BANK	)	,
    IkireMicrofinanceBank(	"090279"	,	"Ikire Microfinance Bank"	,	Type.BANK	)	,
    MegapraiseMicrofinanceBank(	"090280"	,	"Megapraise Microfinance Bank"	,	Type.BANK	)	,
    MintFinexMicrofinanceBank(	"090281"	,	"MintFinex Microfinance Bank"	,	Type.BANK	)	,
    AriseMicrofinanceBank(	"090282"	,	"Arise Microfinance Bank"	,	Type.BANK	)	,
    NnewWomenMicrofinanceBank(	"090283"	,	"Nnew Women Micro finance Bank"	,	Type.BANK	)	,
    FirstOptionMicrofinanceBank(	"090285"	,	"First Option Microfinance Bank"	,	Type.BANK ),
    SafeHavenMicrofinanceBank(	"090286"	,	"Safe Haven Microfinance Bank"	,	Type.BANK	)	,
    AssetMatrixMicrofinanceBank(	"090287"	,	"Asset Matrix Microfinance Bank"	,	Type.BANK	)	,
    PillarMicrofinanceBank(	"090289"	,	"Pillar Microfinance Bank"	,	Type.BANK	)	,
    FCTMicrofinanceBank(	"090290"	,	"FCT Microfinance Bank"	,	Type.BANK	)	,
    HalalCreditMicrofinanceBank(	"090291"	,	"Halal Credit Microfinance Bank"	,	Type.BANK	)	,
    AfekhafeMicrofinanceBank(	"090292"	,	"Afekhafe Microfinance Bank"	,	Type.BANK	)	,
    BrethrenMicrofinanceBank(	"090293"	,	"Brethren Microfinance Bank"	,	Type.BANK	)	,
    EagleFlightMicrofinanceBank(	"090294"	,	"Eagle Fligh tMicrofinance Bank	"	,	Type.BANK	)	,
    OmiyeMicrofinanceBank(	"090295"	,	"Omiye Microfinance Bank"	,	Type.BANK	)	,
    PolyunwanaMicrofinanceBank(	"	090296	"	,	"Polyunwana Microfinance Bank"	,	Type.BANK	)	,
    AlertMicrofinanceBank(	"090297"	,	"Alert Microfinance Bank"	,	Type.BANK	)	,
    FedPolyNasarawaMicrofinanceBank(	"090298"	,	"FedPoly Nasarawa Microfinance Bank"	,	Type.BANK	)	,
    KontagoraMicrofinanceBank(	"090299"	,	"Kontagora Microfinance Bank"	,	Type.BANK	)	,
    PurplemoneyMicrofinanceBank(	"	090303	"	,	"		PurplemoneyMicrofinanceBank	"	,	Type.BANK	)	,
    EvangelMicrofinanceBank(	"090304"	,	"Evangel Microfinance Bank"	,	Type.BANK	)	,
    SulspapMicrofinanceBank(	"090305"	,	"Sulspap Microfinance Bank"	,	Type.BANK	)	,
    AramokoMicrofinanceBank(	"090307"	,	"Aramoko Microfinance Bank"	,	Type.BANK	)	,
    BrightwayMicrofinanceBank(	"090308"	,	"Brightway Microfinance Bank"	,	Type.BANK	)	,
    EdFinMicrofinanceBank(	"090310"	,	"EdFin Microfinance Bank"	,	Type.BANK	)	,
    UCMicrofinanceBank(	"090315"	,	"U&C Microfinance Bank"	,	Type.BANK	)	,
    PatrickGoldMicrofinanceBank(	"090317"	,	"Patrick Gold Microfinance Bank"	,	Type.BANK	)	,
    FederalUniversityDutseMicrofinanceBank(	"090318"	,	"Federal University Dutse MicrofinanceBank"	,	Type.BANK	)	,
    KadPolyMicrofinanceBank(	"090320"	,	"KadPoly Microfinance Bank"	,	Type.BANK	)	,
    MayFairMicrofinanceBank(	"090321"	,	"MayFair Microfinance Bank"	,	Type.BANK	)	,
    RephidimMicrofinanceBank(	"090322"	,	"Rephidim Microfinance Bank",	Type.BANK	)	,
    MainlandMicrofinanceBank(	"090323"	,	"Mainland Microfinance Bank"	,	Type.BANK	)	,
    IkenneMicrofinanceBank(	"090324"	,	"Ikenne Microfinance Bank"	,	Type.BANK	)	,
    Sparkle(	"090325"	,	"Sparkle"	,	Type.BANK	)	,
    BalogunGambariMicrofinanceBank(	"090326"	,	"Balogun Gambari Microfinance Bank	"	,	Type.BANK	)	,
    TrustMicrofinanceBank(	"090327"	,	"Trust Microfinance Bank"	,	Type.BANK	)	,
    Eyowo(	"090328"	,	"Eyowo"	,	Type.BANK	)	,
    NeptuneMicrofinanceBank(	"090329"	,	"Neptune Microfinance Bank"	,	Type.BANK	)	,
    UNAABMicrofinanceBank(	"090331"	,	"UNAAB Microfinance Bank"	,	Type.BANK	)	,
    EvergreenMicrofinanceBank(	"090332"	,	"Evergreen Microfinance Bank"	,	Type.BANK	)	,
    OcheMicrofinanceBank(	"090333"	,	"Oche Microfinance Bank	"	,	Type.BANK	)	,
    IyeruOkinMicrofinanceBank(	"090337"	,	"IyeruOkin Microfinance Bank"	,	Type.BANK	)	,
    JessefieldMicrofinanceBank(	"090352"	,	"Jessefield Microfinance Bank"	,	Type.BANK	)	,
    BIPCMicrofinanceBank(	"090336"	,	"BIPC Microfinance Bank"	,	Type.BANK	)	,
    OAUMicrofinanceBank(	"090345"	,	"OAU Microfinance Bank"	,	Type.BANK	)	,
    NassarawaMicrofinanceBank(	"090349"	,	"Nassarawa Microfinance Bank"	,	Type.BANK	)	,
    CashConnectMicrofinanceBank(	"090360"	,	"Cash Connect Microfinance Bank"	,	Type.BANK	)	,
    MolusiMicrofinanceBank(	"090362"	,	"Molusi Microfinance Bank"	,	Type.BANK	)	,
    HeadwayMicrofinanceBank(	"090363"	,	"Headway Microfinance Bank"	,	Type.BANK	)	,
    NutureMicrofinanceBank(	"090364"	,	"Nuture Microfinance Bank"	,	Type.BANK	)	,
    CorestepMicrofinanceBank(	"090365"	,	"Corestep Microfinance Bank"	,	Type.BANK	)	,
    FirmusMicrofinanceBank(	"090366"	,	"Firmus Microfinance Bank"	,	Type.BANK	)	,
    SeedvestMicrofinanceBank(	"090369"	,	"Seedvest Microfinance Bank"	,	Type.BANK	)	,
    IlisanMicrofinanceBank(	"090370"	,	"Ilisan Microfinance Bank"	,	Type.BANK	)	,
    LegendMicrofinanceBank(	"090372"	,	"Legend Microfinance Bank"	,	Type.BANK	)	,
    ThinkFinanceMicrofinanceBank(	"090373"	,	"ThinkFinance Microfinance Bank"	,	Type.BANK	)	,
    CoastlineMicrofinanceBank(	"090374"	,	"Coastline Microfinance Bank"	,	Type.BANK	)	,
    AppleMicrofinanceBank(	"090376"	,	"Apple Microfinance Bank"	,	Type.BANK	)	,
    IsaleoyoMicrofinanceBank(	"090377"	,	"Isaleoyo Micro financeBank"	,	Type.BANK	)	,
    NewGoldenPasturesMicrofinanceBank(	"090378"	,	"NewGoldenPastures Microfinance Bank"	,	Type.BANK	)	,
    GTIMicrofinanceBank(	"090385"	,	"GTI Microfinance Bank"	,	Type.BANK	)	,
    InterlandMicrofinanceBank(	"090386"	,	"Interland Microfinance Bank"	,	Type.BANK	)	,
    EKReliableMicrofinanceBank(	"090389"	,	"EK-Reliable Microfinance Bank"	,	Type.BANK	)	,
    DavodaniMicrofinanceBank(	"090391"	,	"Davodani Microfinance Bank"	,	Type.BANK	)	,
    ConproMicrofinanceBank(	"090380"	,	"Conpro Microfinance Bank"	,	Type.BANK	)	,
    BridgewayMicrofinanceBank(	"090393"	,	"Bridgeway Microfinance Bank"	,	Type.BANK	)	,
    AmacMicrofinanceBank(	"090394"	,	"Amac Microfinance Bank"	,	Type.BANK	)	,
    BorguMicrofinanceBank(	"090395"	,	"Borgu Microfinance Bank"	,	Type.BANK	)	,
    OscotechMicrofinanceBank(	"090396"	,	"Oscotech Microfinance Bank"	,	Type.BANK	)	,
    NwannegadiMicrofinanceBank(	"090399"	,	"Nwannegadi Microfinance Bank"	,	Type.BANK	)	,
    FederalPolytechnicNekedeMicrofinanceBank(	"090398"	,	"Federal PolytechnicNekede MicrofinanceBank"	,	Type.BANK	)	,
    ShepherdTrustMicrofinanceBank(	"090401"	,	"Shepherd Trust Microfinance Bank"	,	Type.BANK	)	,
    UDAMicrofinanceBank(	"090403"	,	"UDA Microfinance Bank"	,	Type.BANK	)	,
    OlowolagbaMicrofinanceBank(	"090404"	,	"Olowolagba Microfinance Bank"	,	Type.BANK	)	,
    MoniepointMicrofinanceBank(	"090405"	,	"Moniepoint Microfinance Bank"	,	Type.BANK	)	,
    BusinessSupportMicrofinanceBank(	"090406"	,	"Business Support MicrofinanceBank"	,	Type.BANK	)	,
    FCMBBETA(	"090409"	,	"FCMB BETA"	,	Type.BANK	)	,
    GMBMicrofinanceBank(	"090408"	,	"GMB Microfinance Bank"	,	Type.BANK	)	,
    MaritimeMicrofinanceBank(	"090410"	,	"Maritime Microfinance Bank"	,	Type.BANK	)	,
    GiginyaMicrofinancebank(	"090411"	,	"Giginya Microfinance Bank"	,	Type.BANK	)	,
    PreeminentMicrofinanceBank(	"090412"	,	"Preeminent Microfinance Bank"	,	Type.BANK	)	,
    RigoMicrofinanceBank(	"090433"	,	"Rigo Microfinance Bank"	,	Type.BANK	)	,
    BOIMicrofinanceBank(	"090444"	,	"BOI Microfinance Bank"	,	Type.BANK	)	,
    MoyofadeMicrofinanceBank(	"090448"	,	"Moyofade Microfinance Bank"	,	Type.BANK	)	,
    MkoboMicrofinanceBank(	"090455"	,	"Mkobo MicrofinanceBank"	,	Type.BANK	)	,
    RehobothMicrofinanceBank(	"090463"	,	"Rehoboth Microfinance Bank"	,	Type.BANK	)	,
    UnimaidMicrofinanceBank(	"090464	"	,	"Unimaid Microfinance Bank"	,	Type.BANK	)	,
    OLOFINOWENAMicrofinanceBank(	"090468"	,	"OLOFINOWENA Microfinance Bank"	,	Type.BANK	)	,
    AssetsMicrofinanceBank(	"090473"	,	"Assets Microfinance Bank"	,	Type.BANK	)	,
    UniUyoMicrofinanceBank(	"090338"	,	"Uni Uyo Microfinance Bank"	,	Type.BANK	)	,
    YCTMicrofinanceBank(	"090466"	,	"YCT Microfinance Bank"	,	Type.BANK	)	,
    GoodNeigboursMicrofinanceBank(	"090467"	,	"Good Neigbours Microfinance Bank"	,	Type.BANK	)	,
    OluchukwuMicrofinanceBank(	"090471"	,	"Oluchukwu Microfinance Bank"	,	Type.BANK	)	,
    MaintrustMicrofinanceBank(	"090465"	,	"Maintrust Microfinance Bank"	,	Type.BANK	)	,
    AniochaMicrofinancebank(	"090469"	,	"Aniocha Microfinance Bank"	,	Type.BANK	)	,
    CaretakerMicrofinanceBank(	"090472"	,	"Caretaker Microfinance Bank"	,	Type.BANK	)	,
    GiantStrideMicrofinanceBank(	"090475"	,	"GiantStride Microfinance Bank"	,	Type.BANK	)	,
    BalogunFulaniMicrofinanceBank(	"090181"	,	"BalogunFulani Microfinance Bank"	,	Type.BANK	)	,
    VerdantMicrofinanceBank(	"090474"	,	"Verdant Microfinance Bank"	,	Type.BANK	)	,
    ChanganRTSMicrofinanceBank(	"090470"	,	"ChanganRTS Microfinance Bank"	,	Type.BANK	)	,
    AnchorageMicrofinanceBank(	"090476"	,	"Anchorage Microfinance Bank"	,	Type.BANK	)	,
    LightMFB(	"090477"	,	"Light MFB"	,	Type.BANK	)	,
    CintrustMicrofinanceBank(	"090480"	,	"Cintrust Microfinance Bank"	,	Type.BANK	)	,
    FedethMicrofinanceBank(	"090482"	,	"Fedeth Microfinance Bank"	,	Type.BANK	)	,
    AdaMicrofinanceBank(	"090483"	,	"Ada Microfinance Bank"	,	Type.BANK	)	,
    IbuAjeMicrofinanceBank(	"090488"	,	"Ibu-Aje Microfinance Bank"	,	Type.BANK	)	,
    AlvanaMicrofinanceBank(	"090489"	,	"Alvana Microfinance Bank"	,	Type.BANK	)	,
    ChukwunenyeMFB(	"090490"	,	"Chukwunenye MFB"	,	Type.BANK	)	,
    NsukMFB(	"	090491"	,	"Nsuk MFB"	,	Type.BANK	)	,
    OraukwuMFB(	"090492"	,	"Oraukwu MFB"	,	Type.BANK	)	,
    BojiMFB(	"090494"	,	"Boji MFB"	,	Type.BANK	)	,
    GoodnewsMicrofinanceBank(	"090495"	,	"GoodnewsMicrofinanceBank"	,	Type.BANK	)	,
    RandalphaMicrofinanceBank(	"090496"	,	"Randalpha Microfinance Bank"	,	Type.BANK	)	,
    PristineDivitisMicrofinanceBank(	"090499"	,	"Pristine Divitis Microfinance Bank"	,	Type.BANK	)	,
    ShalomMicrofinanceBank(	"090502"	,	"Shalom Microfinance Bank"	,	Type.BANK	)	,
    ProjectsMicrofinanceBank(	"090503"	,	"Projects Microfinance Bank"	,	Type.BANK	)	,
    ZikoraMicrofinanceBank(	"090504"	,	"Zikora Microfinance Bank"	,	Type.BANK	)	,
    NigerianPrisonsMicrofinanceBank(	"090505"	,	"Nigerian Prisons Microfinance Bank	"	,	Type.BANK	)	,
    SolidAllianzeMFB(	"090506"	,	"Solid Allianze MFB"	,	Type.BANK	)	,
    FIMSMFB(	"090507"	,	"FIMS MFB"	,	Type.BANK	)	,
    SEAPMicrofinanceBank(	"090513"	,	"SEAP Microfinance Bank"	,	Type.BANK	)	,
    RIMAGrowthPathwayMicrofinanceBank(	"090515"	,	"RIMA Growth Pathway Microfinance Bank"	,	Type.BANK	)	,
    NumoMicrofinanceBank(	"090516"	,	"Numo Microfinance Bank"	,	Type.BANK	)	,
    UhuruMicrofinanceBank(	"090517"	,	"Uhuru Microfinance Bank"	,	Type.BANK	)	,
    AfemaiMicrofinanceBank(	"090518"	,	"Afemai Microfinance Bank	"	,	Type.BANK	)	,
    IbomaFadamaMicrofinanceBank(	"090519"	,	"Iboma Fadama MicrofinanceBank"	,	Type.BANK	)	,
    ChaseMicrofinanceBank(	"090523"	,	"Chase Microfinance Bank"	,	Type.BANK	)	,
    SolidrockmicrofinanceBank(	"090524"	,	"Solidrock Microfinance Bank"	,	Type.BANK	)	,
    TripleAMicrofinanceBank(	"090525"	,	"TripleA Microfinance Bank"	,	Type.BANK	)	,
    CrescentMicrofinanceBank(	"090526"	,	"Crescent Microfinance Bank"	,	Type.BANK	)	,
    OjokoroMicrofinanceBank(	"090527"	,	"Ojokoro Microfinance Bank"	,	Type.BANK	)	,
    MgbidiMicrofinanceBank(	"090528"	,	"Mgbidi Microfinance Bank"	,	Type.BANK	)	,
    AmpersandMicrofinanceBank(	"090529"	,	"Ampersand Microfinance Bank"	,	Type.BANK	)	,
    ConfidenceMFB(	"090530"	,	"Confidence MFB"	,	Type.BANK	)	,
    AkuMicrofinanceBank(	"090531"	,	"Aku Microfinance Bank"	,	Type.BANK	)	,
    PolybadanMicrofinanceBank(	"090534"	,	"Polybadan Microfinance Bank"	,	Type.BANK	)	,
    IkoyiOsunMicrofinanceBank(	"090536"	,	"Ikoyi-Osun Microfinance Bank"	,	Type.BANK	)	,
    LobremMicrofinanceBank(	"090537"	,	"Lobrem Microfinance Bank"	,	Type.BANK	)	,
    BluePrintInvestmentsMicrofinanceBank(	"090538"	,	"BluePrint Investments MicrofinanceBank"	,	Type.BANK	)	,
    EnrichMicrofinanceBank(	"090539"	,	"EnrichMicrofinanceBank"	,	Type.BANK	)	,
    AztecMicrofinanceBank(	"090540"	,	"Aztec Microfinance Bank"	,	Type.BANK	)	,
    ExcellentMicrofinanceBank(	"090541"	,	"Excellent Microfinance Bank	"	,	Type.BANK	)	,
    OtuoMicrofinanceBank(	"090542"	,	"Otuo Microfinance Bank	"	,	Type.BANK	)	,
    IwoamaMicrofinanceBank(	"090543"	,	"Iwoama Microfinance Bank	"	,	Type.BANK	)	,
    AspireMicrofinanceBank(	"090544"	,	"Aspire Microfinance Bank	"	,	Type.BANK	)	,
    AbulesoroMicrofinanceBank(	"090545"	,	"Abulesoro Microfinance Bank	"	,	Type.BANK	)	,
    IjebuIfeMicrofinanceBank(	"090546"	,	"Ijebu-Ife Microfinance Bank	"	,	Type.BANK	)	,
    RockshieldMicrofinanceBank(	"090547"	,	"Rockshield Microfinance Bank	"	,	Type.BANK	)	,
    AllyMicrofinanceBank(	"090548"	,	"Ally Microfinance Bank"	,	Type.BANK	)	,
    KCMicrofinanceBank(	"090549"	,	"KC Microfinance Bank"	,	Type.BANK	)	,
    GreenEnergyMicrofinanceBank(	"090550"	,	"Green Energy Microfinance Bank"	,	Type.BANK	)	,
    FairMoneyMicrofinanceBank(	"090551"	,	"FairMoney Microfinance Bank"	,	Type.BANK	)	,
    ConsistentTrustMicrofinanceBank(	"090553"	,	"Consistent Trust MicrofinanceBank"	,	Type.BANK	)	,
    KayveeMicrofinanceBank(	"090554"	,	"Kayvee Microfinance Bank"	,	Type.BANK	)	,
    BishopGateMicrofinanceBank(	"090555"	,	"BishopGate Microfinance Bank"	,	Type.BANK	)	,
    EgwafinMicrofinanceBank(	"090556"	,	"EgwafinMicrofinance Bank"	,	Type.BANK	)	,
    LifegateMicrofinanceBank(	"090557"	,	"Lifegate Microfinance Bank"	,	Type.BANK	)	,
    ShongomMicrofinanceBank(	"090558"	,	"Shongom Microfinance Bank"	,	Type.BANK	)	,
    ShieldMicrofinanceBank(	"090559"	,	"Shield Microfinance Bank"	,	Type.BANK	)	,
    TanadiMicrofinanceBank(	"090560"	,	"Tanadi Microfinance Bank"	,	Type.BANK	)	,
    AkuchuckwuMicrofinanceBank(	"090561"	,	"Akuchuckwu Microfinance Bank	"	,	Type.BANK	)	,
    CedarMicrofinanceBank(	"090562"	,	"CedarMicrofinanceBank"	,	Type.BANK	)	,
    BaleraMicrofinanceBank(	"090563"	,	"Balera Microfinance Bank"	,	Type.BANK	)	,
    SupremeMicrofinanceBank(	"090564"	,	"Supreme Microfinance Bank"	,	Type.BANK	)	,
    OkeAroOredegbeMicrofinanceBank(	"090565"	,	"Oke-AroOredegbe Microfinance Bank"	,	Type.BANK	)	,
    OkukuMicrofinanceBank(	"090566"	,	"Okuku Microfinance Bank"	,	Type.BANK	)	,
    OrokamMicrofinanceBank(	"090567"	,	"Orokam Microfinance Bank"	,	Type.BANK	)	,
    BroadviewMicrofinanceBank(	"090568"	,	"Broadview Microfinance Bank"	,	Type.BANK	)	,
    QubeMicrofinanceBank(	"090569"	,	"Qube Microfinance Bank"	,	Type.BANK	)	,
    IyamoyeMicrofinanceBank(	"090570"	,	"Iyamoye Microfinance Bank"	,	Type.BANK	)	,
    IlaroPolyMicrofinanceBank(	"090571"	,	"Ilaro Poly Microfinance Bank"	,	Type.BANK	)	,
    EWTMicrofinanceBank(	"090572"	,	"EWT Microfinance Bank"	,	Type.BANK	)	,
    SnowMFB(	"090573"	,	"Snow MFB"	,	Type.BANK	)	,
    FirstMidasMicrofinanceBank(	"090575"	,	"First Midas Microfinance Bank"	,	Type.BANK	)	,
    OctopusMicrofinanceBank(	"090576"	,	"Octopus Microfinance Bank"	,	Type.BANK	)	,
    GbedeMicrofinanceBank(	"090579"	,	"Gbede Microfinance Bank"	,	Type.BANK	)	,
    OtechMicrofinanceBank(	"090580"	,	"Otech Microfinance Bank"	,	Type.BANK	)	,
    StatesideMicrofinanceBank(	"090583"	,	"Stateside Microfinance Bank"	,	Type.BANK	)	,
    GOLDMANMFB(	"090574"	,	"GOLDMAN MFB"	,	Type.BANK	)	,
    NkpoluUstMFB(	"090535"	,	"Nkpolu-Ust MFB"	,	Type.BANK	)	,
    IwadeMFBLtd(	"090578"	,	"IwadeMFB Ltd"	,	Type.BANK	)	,
    MicrobizMFB(	"090587"	,	"Microbiz MFB"	,	Type.BANK	)	,
    OrisunMFB(	"090588"	,	"Orisun MFB	"	,	Type.BANK	)	,
    MercuryMFB(	"090589"	,	"Mercury MFB"	,	Type.BANK	)	,
    GabsynMicrofinanceBankLimited(	"090591"	,	"Gabsyn Microfinance Bank Limited"	,	Type.BANK	)	,
    TasuedMicrofinanceBank(	"090593"	,	"Tasued Microfinance Bank"	,	Type.BANK	)	,
    KenechukwuMicrofinanceBank(	"090602"	,	"Kenechukwu Microfinance Bank"	,	Type.BANK	)	,
    WayaMicrofinanceBank(	"090950"	,	"Waya Microfinance Bank"	,	Type.BANK	)	,
    IBAMicrofinanceBank(	"090598"	,	"IBA Microfinance Bank"	,	Type.BANK	)	,
    IslandMicrofinanceBank(	"090584"	,	"Island Microfinance Bank"	,	Type.BANK	)	,
    AveMariaMicrofinanceBank(	"090600"	,	"Ave Maria Microfinance Bank"	,	Type.BANK	)	,
    AkpoMicrofinanceBank(	"090608"	,	"Akpo Microfinance Bank"	,	Type.BANK	)	,
    UmmahMicrofinanceBank(	"090609"	,	"Ummah Microfinance Bank"	,	Type.BANK	)	,
    AmoyeMicrofinanceBank(	"090610"	,	"Amoye Microfinance Bank"	,	Type.BANK	)	,
    MedefMicrofinanceBank(	"090612"	,	"Medef Microfinance Bank"	,	Type.BANK	)	,
    IBOLOMicrofinanceBank(	"090532"	,	"IBOLO Microfinance Bank"	,	Type.BANK	)	,
    BancCorpMFB(	"090581"	,	"BancCorp MFB"	,	Type.BANK	)	,
    FlourishMFB(	"090614"	,	"Flourish MFB"	,	Type.BANK	)	,
    BeststarMFB(	"090615"	,	"Beststar MFB"	,	Type.BANK	)	,
    RayyanMFB(	"090616"	,	"Rayyan MFB"	,	Type.BANK	)	,
    MacrodMFB(	"090603"	,	"Macrod MFB"	,	Type.BANK	)	,
    IyinEkitiMFB(	"090620"	,	"IyinEkiti MFB"	,	Type.BANK	)	,
    GidauniyarAlheriMFB(	"090621"	,	"Gidauniyar Alheri MFB"	,	Type.BANK	)	,
    CreditvilleMFB(	"090611"	,	"Creditville MFB"	,	Type.BANK	)	,
    MABAllianzMFB(	"090623"	,	"MABAllianz MFB"	,	Type.BANK	)	,
    KKUMFB(	"090606"	,	"KKU MFB"	,	Type.BANK	)	,
    FET(	"100001"	,	"FET"	,	Type.BANK	)	,
    Paga(	"100002"	,	"Paga"	,	Type.BANK	)	,
    ParkwayReadyCash(	"100003"	,	"Parkway-ReadyCash"	,	Type.BANK	)	,
    Paycom(	"	100004"	,	"Paycom(Opay)"	,	Type.BANK	)	,
    Cellulant(	"100005"	,	"Cellulant"	,	Type.BANK	)	,
    eTranzact(	"100006"	,	"eTranzact"	,	Type.BANK	)	,
    StanbicIBTCeasewallet(	"100007"	,	"StanbicIBTC @easewallet"	,	Type.BANK	)	,
    EcobankXpressAccount(	"100008"	,	"Ecobank Xpress Account"	,	Type.BANK	)	,
    GTMobile(	"100009"	,	"GTMobile"	,	Type.BANK	)	,
    TeasyMobile(	"100010"	,	"TeasyMobile"	,	Type.BANK	)	,
    Mkudi(	"100011"	,	"Mkudi"	,	Type.BANK	)	,
    VTNetworks(	"100012"	,	"VTNetworks"	,	Type.BANK	)	,
    AccessMobile(	"100013"	,	"AccessMobile"	,	Type.BANK	)	,
    FBNMobile(	"100014"	,	"FBNMobile"	,	Type.BANK	)	,
    Kegow(	"100036"	,	"Kegow(Chamsmobile)"	,	Type.BANK	)	,
    FortisMobile(	"100016"	,	"FortisMobile"	,	Type.BANK	)	,
    Hedonmark(	"100017"	,	"Hedonmark"	,	Type.BANK	)	,
    ZenithMobile(	"100018"	,	"ZenithMobile"	,	Type.BANK	)	,
    FidelityMobile(	"100019"	,	"FidelityMobile	"	,	Type.BANK	)	,
    MoneyBox(	"100020"	,	"MoneyBox"	,	Type.BANK	)	,
    Eartholeum(	"100021"	,	"Eartholeum"	,	Type.BANK	)	,
    GoMoney(	"100022"	,	"GoMoney"	,	Type.BANK	)	,
    TagPay(	"100023"	,	"TagPay	"	,	Type.BANK	)	,
    ZinternetNigeraLimited(	"100025"	,	"Zinternet Nigera Limited	"	,	Type.BANK	)	,
    OneFinance(	"100026"	,	"OneFinance"	,	Type.BANK	)	,
    InnovectivesKesh(	"100029"	,	"Innovectives Kesh"	,	Type.BANK	)	,
    EcoMobile(	"100030"	,	"EcoMobile"	,	Type.BANK	)	,
    FCMBEasyAccount(	"100031"	,	"FCMB Easy Account"	,	Type.BANK	)	,
    ContecGlobalInfotechLimited(	"100032"	,	"Contec Global Infotech Limited(NowNow)"	,	Type.BANK	)	,
    PalmPayLimited(	"100033"	,	"PalmPay Limited"	,	Type.BANK	)	,
    ZenithEazyWallet(	"100034"	,	"Zenith Eazy Wallet"	,	Type.BANK	)	,
    AccessYello(	"100052"	,	"Access Yello"	,	Type.BANK	)	,
    M36(	"100035"	,	"M36"	,	Type.BANK	)	,
    TitanPaystack(	"100039"	,	"Titan Paystack"	,	Type.BANK	)	,
    Taj_Pinspay(	"080002"	,	"Taj_Pinspay"	,	Type.BANK	)	,
    Intellifin(	"100027"	,	"Intellifin"	,	Type.BANK	)	,
    PayAttitudeOnline(	"110001","Pay Attitude Online",Type.BANK),
    FlutterwaveTechnologySolutionsLimited("110002","Flutterwave Technology SolutionsLimited",Type.BANK),
    InterswitchLimited(	"110003",	"Interswitch Limited",Type.BANK	)	,
    FirstAppleLimited(	"110004",	"FirstApple Limited"	,Type.BANK	)	,
    ineCardManagementLimited(	"110005",	"3line CardManagement Limited",Type.BANK	),
    PaystackPaymentLimited(	"110006"	,"Paystack Payment Limited",	Type.BANK)	,
    TeamaptLimited(	"110007","Teamapt Limited",Type.BANK),
    CyberspaceLimited("110014",	"Cyberspace Limited",Type.BANK),
    Vas2netsLimited("110015",	"Vas2nets Limited",Type.BANK),
    Crowdforce(	"110017","Crowdforce",Type.BANK),
    Prophius("110032","Prophius",Type.BANK),
    AccelerexNetworkLimited("	090202","Accelerex Network Limited",Type.BANK)	,
    NIPVirtualBank(	"999999","NIP Virtual Bank",Type.BANK)	,
    LeadremitLimited("110044"	,"Leadremit Limited",Type.BANK),
    ninePaymentServiceBank(	"120001",	"9Payment Service Bank",Type.BANK),
    HopePSB("120002",	"Hope PSB",Type.BANK	),
    MoMoPSB("120003",	"MoMo PSB",Type.BANK	),
    SmartCashPSB("120004","SmartCash PSB",	Type.BANK);
    /*
    AccessDiamondBank("000005", "Access (Diamond) Bank", Type.BANK),
    AccessBank("000014", "Access Bank", Type.BANK),
    CitiBank("000009", "Citi Bank", Type.BANK),
    EcobankBank("000010", "Ecobank Bank", Type.BANK),
    EnterpriseBank("000019", "Enterprise Bank", Type.BANK),
    FCMB("000003", "FCMB", Type.BANK),
    FidelityBank("000007", "Fidelity Bank", Type.BANK),
    FirstBankOfNigeria("000016", "First Bank of Nigeria", Type.BANK),
    GlobusBank("000027", "Globus Bank", Type.BANK),
    GTBankPlc("000013", "GT Bank Plc", Type.BANK),
    HeritageBank("000020", "Heritage Bank", Type.BANK),
    JAIZBank("000006", "JAIZ Bank", Type.BANK),
    KeystoneBank("000002", "Keystone Bank", Type.BANK),
    PolarisBank("000008", "Polaris Bank", Type.BANK),
    ProvidusBank("000023", "Providus Bank ", Type.BANK),
    RandMerchantBank("000024", "Rand Merchant Bank", Type.BANK),
    StanbicIBTCBank("000012", "Stanbic IBTC Bank", Type.BANK),
    StandardChartered("000021", "Standard Chartered", Type.BANK),
    SterlingBank("000001", "Sterling Bank", Type.BANK),
    SuntrustBank("000022", "Suntrust Bank", Type.BANK),
    TajBank("000026", "Taj Bank", Type.BANK),
    TitanTrustBank("000025", "Titan Trust Bank", Type.BANK),
    UnionBank("000018", "Union Bank", Type.BANK),
    UnitedBankForAfrica("000004", "United Bank for Africa", Type.BANK),
    UnityBank("000011", "Unity Bank", Type.BANK),
    WemaBank("000017", "Wema Bank", Type.BANK),
    ZenithBankPlc("000015", "Zenith Bank Plc", Type.BANK),

    //MMOs
    ParalleBank("090004", "Parralex Microfinance Bank", Type.MMO),
    PaymentServiceBank("120001", "9Payment Service Bank", Type.MMO),
    AccessYello("100052", "Access Yello", Type.MMO),
    AccessMobile("100013", "AccessMobile", Type.MMO),
    Cellulant("100005", "Cellulant", Type.MMO),
    ContecGlobalInfoLtd("100032", "Contec Global Info Ltd (NowNow)", Type.MMO),
    Eartholeum("100021", "Eartholeum", Type.MMO),
    EcobankXpressAccount("100008", "Ecobank Xpress Account", Type.MMO),
    EcoMobile("100030", "EcoMobile", Type.MMO),
    eTranzact("100006", "eTranzact", Type.MMO),
    FBNMobile("100014", "FBNMobile", Type.MMO),
    FCMBEasyAccount("100031", "FCMB Easy Account", Type.MMO),
    FidelityMobile("100019", "Fidelity Mobile", Type.MMO),
    FortisMobile("100016", "FortisMobile", Type.MMO),
    GoMoney("100022", "GoMoney", Type.MMO),
    GTMobile("100009", "GTMobile", Type.MMO),
    Hedonmark("100017", "Hedonmark", Type.MMO),
    HopePSB("120002", "HopePSB", Type.MMO),
    InnovectivesKesh("100029", "Innovectives Kesh", Type.MMO),
    Intellifin("100027", "Intellifin", Type.MMO),
    Kegow("100015", "Kegow", Type.MMO),
    Mkudi("100011", "Mkudi", Type.MMO),
    MoneyBox("100020", "MoneyBox", Type.MMO),
    OneFinance("100026", "One Finance", Type.MMO),
    Paga("100002", "Paga", Type.MMO),
    PalmPayLimited("100033", "PalmPay Limited", Type.MMO),
    ParkwayReadyCash("100003", "Parkway-ReadyCash", Type.MMO),
    PaycomOpay("100004", "Paycom(Opay)", Type.MMO),
    StanbicIBTCEaseWallet("100007", "Stanbic IBTC @ease wallet", Type.MMO),
    TagPay("100023", "TagPay", Type.MMO),
    TeasyMobile("100010", "TeasyMobile", Type.MMO),
    VTNetworks("100012", "VTNetworks", Type.MMO),
    ZenithMobile("100018", "ZenithMobile", Type.MMO),
    ZinternetNigeraLimited("100025", "Zinternet Nigera Limited", Type.MMO);

    */
    //Additional Banks and MMO

    
    private String code, displayName;
    private Type type;

    Bank(String code, String displayName, Type type) {
        this.code = code.trim();
        this.displayName = displayName.trim();
        this.type = type;
    }

    public static Bank byCode(String code) {
        for(Bank bank : Bank.values()) {
            if(bank.code.equals(code)) {
                return bank;
            }
        }

        return null;
    }

    public static List<Bank> byType(Type type) {
        List<Bank> list = new ArrayList<>();
        for(Bank bank : Bank.values()) {
            if(bank.type == type) {
                list.add(bank);
            }
        }

        return list;
    }

    public String getCode() {
        return code;
    }

    public String getDisplayName() {
        return displayName;
    }

    public enum Type {
        BANK, MMO
    }
}
